swagger: "2.0"
info:
  description: 'LKB API'
  version: '1.0.0'
  title: 'LKB API'
tags:

  - name: "Questionnaire"
    description: Updating and getting information about Questionnaire

basePath: /api
paths:


  /application/{id}/questionnaire/:
    get:
      summary: get questionnaire
      description: return questionnaire
      tags:
        - Questionnaire
      operationId: getQuestionnaire
      parameters:
        - $ref: '#/parameters/ApplicationId'
      responses:
        200:
          description: OK
          schema:
            type: string
    post:
      summary: update Questionnaire
      description: update Questionnaire
      tags:
        - Questionnaire
      operationId: updateQuestionnaire
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/ApplicationId'
        - in: body
          required: true
          name: form
          schema:
            type: string
      responses:
        200:
          description: OK



parameters:
  ApplicationId:
    name: id
    in: path
    description: application id
    required: true
    type: string







